# Site settings
title: Andres Becker's personal page
author:
  name: Andres Becker
  email: andres.becker@tum.de
  linkedin: https://www.linkedin.com/in/andres-becker/
  github: https://github.com/andresbecker
  github_username: andresbecker

description: > # this means to ignore newlines until "show_excerpts:"
  Andres Becker technical and learning notes
url: "https://andresbecker.github.io/" # the base hostname & protocol for your site

minima:
  date_format: "%b %-d, %Y"

# Build settings
markdown: kramdown
plugins:
 - jekyll-feed
 - jekyll-seo-tag

# Build settings
#theme: minima
