# Site settings
title: About me
email: andres.becker@tum.de
description: > This should say something about me...
More info... # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://andresbecker.github.io/" # the base hostname & protocol for your site

twitter_username:
github_username: andresbecker

# Build settings
markdown: kramdown

theme: jekyll-theme-slate